#!/bin/sh
#
# PROVIDE: caddy
# REQUIRE: NETWORKING
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable caddy:
# caddy_enable (bool):        Set to "NO" by default.
#                             Set it to "YES" to enable caddy
#
# caddy_bin_path (str):       Set to "/usr/local/bin/caddy" by default.
#                             Provides the path to the caddy server executable
#
# caddy_config_path (str):    Set to "/usr/local/www/Caddyfile" by default.
#                             Defines the path for the configuration file caddy will load on boot
#

. /etc/rc.subr

name="caddy"
rcvar="${name}_enable"

load_rc_config ${name}

: ${caddy_enable:="NO"}
: ${caddy_bin_path="/usr/local/bin/caddy"}
: ${caddy_config_path="/usr/local/www/Caddyfile"}

if [ "$caddy_cert_email" = "" ]
then
    echo "rc variable \$caddy_cert_email is not set. Please provide a valid SSL certificate issuer email."
    exit 1
fi

pidfile="/var/run/${name}.pid"
procname="${caddy_bin_path}" #enabled builtin pid checking for start / stop
command="/usr/sbin/daemon"
command_args="-p ${pidfile} -T ${name} -l ${caddy_syslog_facility} -s ${caddy_syslog_level} /usr/bin/env ${caddy_env} ${procname} ${caddy_options} < /dev/null"

start_precmd="caddy_startprecmd"

caddy_startprecmd()
{
        # Clear flags provided by caddy_flags to prevent them being passed to daemon(8)
        rc_flags=""

        if [ ! -e "${pidfile}" ]; then
                install -o "${caddy_user}" -g "${caddy_group}" "/dev/null" "${pidfile}"
        fi
}

required_files="${caddy_config_path}"

run_rc_command "$1"
